repos:
-   repo: local
    hooks:
    -   id: byte-patrol
        name: Byte Patrol
        entry: python -m byte_patrol.pre_commit_hook  # Direct module call
        language: system
        types: [python]
        pass_filenames: false
        args: [
            '--areas', 'documentation',
            '--areas', 'variable naming'
        ]
